### ISSUE TITLE
REST API para MDE

### ISSUE THREAD

**Issue by ramespada** [IGNoficial/argenmap.jquery#2]
Hola!

Buena Iniciativa!

Estaría bueno que la API permita via una consulta obtener el gid para descargar los modelos digitales de elevación del IGN (MDE). Y no tener que acceder a ellas por la plataforma web. Ya hay alguna alternativa para acceder via wget ó curl?

Un saludo!

**Comment by Zalitoar** [comment]
Hola [ramespada](https://github.com/ramespada) esta librería está en desuso desde hace varios años ya. Existe una API para acceder a los modelos de elevación, te recomiendo consultar a la Dirección de Geodesia del IGN sobre cómo se puede acceder.
